events {
    worker_connections 1024;
}

http {
    # Přesměrování HTTP na HTTPS pro všechny domény
    server {
        listen 80;
        server_name zabbix.soc.local wazuh.soc.local grafana.soc.local greenbone.soc.local;
        return 301 https://$host$request_uri;
    }

    # ZABBIX
    server {
        listen 443 ssl;
        server_name zabbix.soc.local;

        ssl_certificate /etc/nginx/certs/soc.local.crt;
        ssl_certificate_key /etc/nginx/certs/soc.local.key;

        location / {
            proxy_pass http://zabbix-web:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # GRAFANA
    server {
        listen 443 ssl;
        server_name grafana.soc.local;

        ssl_certificate /etc/nginx/certs/soc.local.crt;
        ssl_certificate_key /etc/nginx/certs/soc.local.key;

        location / {
            proxy_pass http://grafana:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # WAZUH (Komunikuje interně přes HTTPS na portu 5601)
    server {
        listen 443 ssl;
        server_name wazuh.soc.local;

        ssl_certificate /etc/nginx/certs/soc.local.crt;
        ssl_certificate_key /etc/nginx/certs/soc.local.key;

        location / {
            proxy_pass https://wazuh.dashboard:5601;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_ssl_verify off; 
        }
    }

    # GREENBONE (Odkazujeme na kontejner jménem 'nginx' uvnitř Greenbone sítě)
    server {
        listen 443 ssl;
        server_name greenbone.soc.local;

        ssl_certificate /etc/nginx/certs/soc.local.crt;
        ssl_certificate_key /etc/nginx/certs/soc.local.key;

        location / {
            proxy_pass https://nginx:443;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_ssl_verify off;
        }
    }
}