version: '3.5'

services:
  postgres-server:
    image: postgres:15-alpine
    container_name: zabbix-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_pwd
      - POSTGRES_DB=zabbix
    volumes:
      - ./zabbix_db_data:/var/lib/postgresql/data
    networks:
      - soc-network

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-latest
    container_name: zabbix-server
    restart: unless-stopped
    environment:
      - DB_SERVER_HOST=postgres-server
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_pwd
      - POSTGRES_DB=zabbix
    ports:
      - "10051:10051"
    depends_on:
      - postgres-server
    networks:
      - soc-network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
    container_name: zabbix-web
    restart: unless-stopped
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=postgres-server
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_pwd
      - POSTGRES_DB=zabbix
      - PHP_TZ=Europe/Prague
    ports:
      - "8080:8080"
    depends_on:
      - zabbix-server
    networks:
      - soc-network

networks:
  soc-network:
    external: true