services:
  vulnerability-tests:
    image: registry.community.greenbone.net/community/vulnerability-tests
    volumes:
      - vt_data_vol:/mnt

  scap-data:
    image: registry.community.greenbone.net/community/scap-data
    volumes:
      - scap_data_vol:/mnt

  cert-bund-data:
    image: registry.community.greenbone.net/community/cert-bund-data
    volumes:
      - cert_data_vol:/mnt

  report-formats:
    image: registry.community.greenbone.net/community/report-formats
    volumes:
      - data_vol:/mnt

  data-objects:
    image: registry.community.greenbone.net/community/data-objects
    volumes:
      - data_vol:/mnt

  pg-gvm:
    image: registry.community.greenbone.net/community/pg-gvm:stable
    restart: on-failure
    volumes:
      - psql_data_vol:/var/lib/postgresql
      - psql_socket_vol:/var/run/postgresql

  gvmd:
    image: registry.community.greenbone.net/community/gvmd:stable
    restart: on-failure
    # TADY JSME ODSTRANILI TEN ROZBITÝ PARAMETR. GVMD TEĎ NABĚHNE ČISTĚ.
    volumes:
      - gvmd_data_vol:/var/lib/gvm
      - scap_data_vol:/var/lib/gvm/scap-data/
      - cert_data_vol:/var/lib/gvm/cert-data
      - data_vol:/var/lib/gvm/data-objects/gvmd
      - vt_data_vol:/var/lib/openvas/plugins
      - psql_data_vol:/var/lib/postgresql
      - gvmd_socket_vol:/run/gvmd
      - ospd_openvas_socket_vol:/run/ospd
      - psql_socket_vol:/var/run/postgresql
    depends_on:
      - pg-gvm
      - scap-data
      - cert-bund-data
      - data-objects
      - report-formats
    networks:
      - soc-network
      - default

  gsa:
    image: registry.community.greenbone.net/community/gsa:stable
    restart: on-failure
    ports:
      - "9392:9392"
    volumes:
      - gvmd_socket_vol:/run/gvmd
    depends_on:
      - gvmd

  redis-server:
    image: registry.community.greenbone.net/community/redis-server
    restart: on-failure
    volumes:
      - redis_socket_vol:/run/redis/

  ospd-openvas:
    image: registry.community.greenbone.net/community/ospd-openvas:stable
    restart: on-failure
    init: true
    volumes:
      - ospd_openvas_socket_vol:/run/ospd
      - redis_socket_vol:/run/redis/
      - vt_data_vol:/var/lib/openvas/plugins
    depends_on:
      - redis-server
      - vulnerability-tests

  # TOTO JE NAŠE ZÁCHRANA PRO API (SIDECAR PATTERN)
  gmp-proxy:
    image: alpine/socat
    restart: always
    command: TCP4-LISTEN:9390,fork,reuseaddr UNIX-CONNECT:/run/gvmd/gvmd.sock
    volumes:
      - gvmd_socket_vol:/run/gvmd
    ports:
      - "9390:9390"
    networks:
      - soc-network
    depends_on:
      - gvmd

volumes:
  vt_data_vol:
  scap_data_vol:
  cert_data_vol:
  data_vol:
  psql_data_vol:
  psql_socket_vol:
  gvmd_data_vol:
  gvmd_socket_vol:
  ospd_openvas_socket_vol:
  redis_socket_vol:

networks:
  soc-network:
    external: true